// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQDyyowqji_-kVH09XBePKRsvYJdFM_s',
    appId: '1:325199277423:web:1c88482c299ed929a08c9a',
    messagingSenderId: '325199277423',
    projectId: 'plantlers-c4da1',
    authDomain: 'plantlers-c4da1.firebaseapp.com',
    storageBucket: 'plantlers-c4da1.firebasestorage.app',
    measurementId: 'G-37MH13TCRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB469m1n2a3v9WqK43FpoInj2fAjDDQIdg',
    appId: '1:325199277423:android:08fd459fef85b316a08c9a',
    messagingSenderId: '325199277423',
    projectId: 'plantlers-c4da1',
    storageBucket: 'plantlers-c4da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FCuxrtQIiyncgCigMN4aj_qivxE_K7E',
    appId: '1:325199277423:ios:21f71c8fd6580feea08c9a',
    messagingSenderId: '325199277423',
    projectId: 'plantlers-c4da1',
    storageBucket: 'plantlers-c4da1.firebasestorage.app',
    iosClientId: '325199277423-u4lt5deo6i870mbtjup0t6ahu395aqin.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantlers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-FCuxrtQIiyncgCigMN4aj_qivxE_K7E',
    appId: '1:325199277423:ios:21f71c8fd6580feea08c9a',
    messagingSenderId: '325199277423',
    projectId: 'plantlers-c4da1',
    storageBucket: 'plantlers-c4da1.firebasestorage.app',
    iosClientId: '325199277423-u4lt5deo6i870mbtjup0t6ahu395aqin.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantlers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzQDyyowqji_-kVH09XBePKRsvYJdFM_s',
    appId: '1:325199277423:web:8103636bb30c83b3a08c9a',
    messagingSenderId: '325199277423',
    projectId: 'plantlers-c4da1',
    authDomain: 'plantlers-c4da1.firebaseapp.com',
    storageBucket: 'plantlers-c4da1.firebasestorage.app',
    measurementId: 'G-SF8QDEVLF9',
  );

}